core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('pms.urls')),
]

pms/urls.py
from pms.models import Notification
from django.urls import path
from . import views

urlpatterns = [
	path('', views.IndexView, name = "index"),
	path('home/', views.HomeView, name = "home"),
	path('createproject/', views.CreateProjectView, name = "createproject"),
	path('projects/', views.ProjectsView, name = "projects"),
	path('projects/<int:projectid>/', views.ProjectDetailsView, name = "projectdetails"),
	path('projects/addnewlevel/<int:projectid>/', views.AddNewLevelView, name = "addnewlevel"),
	path('projects/moveproject/<int:projectid>/<int:levelid>/', views.MoveProjectView, name = "moveproject"),
	path('projects/changedetails/<int:projectid>/', views.ChangeProjectDetailsView, name = "changedetails"),
	path('projects/addworker/<int:projectid>/<int:workerid>/', views.AddWorkersView, name = "addworker"),
	path('projects/relieveworker/<int:projectid>/<int:workerid>/', views.RelieveFromProjectView, name = "relieveworker"),
	path('notifications/', views.NotificationsView, name = "notifications"),
	path('notifications/markasread/<int:notificationid>/', views.NotificationMarkAsReadView, name = "markasread"),


	# AUTHENTICATION
	path('login/', views.LoginView, name = "login"),
	path('logout/', views.LogoutView, name = "logout"),
	path('register/', views.RegisterView, name = "register"),
]

pms/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.base import Model
from django.db.models.deletion import PROTECT


class User(AbstractUser):
	company = models.CharField(max_length = 255, null = False, blank = False)


class Project(models.Model):
	owner = models.ForeignKey(User, null = False, blank = False, on_delete = models.CASCADE, related_name = "owner")
	name = models.CharField(max_length = 255, null = False, blank = False)
	description = models.CharField(max_length = 255, null = False, blank = False)
	workers = models.ManyToManyField(User, blank = True)
	all_status = models.ManyToManyField("ProjectLevel", blank = True)
	current_status = models.ForeignKey("ProjectLevel", on_delete = models.CASCADE, blank = True, null = True, related_name = "status")
	date_started = models.DateTimeField(auto_now_add = True)

	
	def __str__(self):
		return str(self.name + " by " + self.owner.username)


class ProjectLevel(models.Model):
	level_tag = models.CharField(max_length = 255)


	def __str__(self):
		return str(self.level_tag)


class Notification(models.Model):
	recipient = models.ForeignKey(User, null = False, blank = False, on_delete = models.CASCADE)
	content = models.CharField(max_length = 255, null = False, blank = False)
	read = models.BooleanField(default = False)
	date_created = models.DateTimeField(auto_now_add = True)


	class Meta:
		ordering = ['-date_created']

	
	def __str__(self):
		return str(self.content)



	

pms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.forms import widgets
from . models import Project, User


class UserRegistrationForm(UserCreationForm):
	username = forms.CharField(max_length = 255)
	firstname = forms.CharField(max_length = 255)
	lastname = forms.CharField(max_length = 255)
	email = forms.EmailField(max_length = 255)
	company = forms.CharField(max_length = 255)


	class Meta:
		model = User
		fields = ('username', 'firstname', 'lastname', 'email', 'company', 'password1', 'password2')

pms/views.py
from pms.forms import UserRegistrationForm
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . models import Notification, Project, ProjectLevel, User
from . utils import get_project_owner_id_username, worker_already_in_project, get_no_of_notifications, get_no_of_projects


def IndexView(request):
	if request.user.is_authenticated:
		return redirect("home")
	else:
		return render(request, 'pms/index.html')


@login_required(login_url='index')
def HomeView(request):
	no_of_project_involved = sum(get_no_of_projects(request))
	return render(request, 'pms/home.html', {'n_p_i': no_of_project_involved, 'number_of_notifications': get_no_of_notifications(request)})


@login_required(login_url='index')
def CreateProjectView(request):
	if request.method == "POST":
		owner = request.user
		name = request.POST['name']
		description = request.POST['description']
		p = Project.objects.create(owner = owner, name = name, description = description)
		pl = ProjectLevel.objects.create(level_tag = "Created")
		p.all_status.add(pl)
		p.current_status = pl
		p.save()
		messages.success(request, "Project Created Successfully!")
		return redirect('projectdetails', projectid = p.pk)

	return render(request, 'pms/createproject.html', {'number_of_notifications': get_no_of_notifications(request)})


@login_required(login_url='index')
def ProjectsView(request):
	projects_as_owner = Project.objects.filter(owner = request.user)
	projects_as_worker = Project.objects.filter(workers__id = request.user.id)
	number_of_projects_as_owner, number_of_projects_as_worker = get_no_of_projects(request)
	return render(request, 'pms/projects.html', {'number_of_projects_as_owner': number_of_projects_as_owner, 'number_of_projects_as_worker': number_of_projects_as_worker,'projects_as_owner': projects_as_owner, 'projects_as_worker': projects_as_worker, 'number_of_notifications': get_no_of_notifications(request)})


@login_required(login_url='index')
def ProjectDetailsView(request, projectid):
	project_workers = Project.objects.get(id = projectid).workers.all()
	project = Project.objects.filter(id = projectid)
	project_statuses = Project.objects.get(id = projectid).all_status.all()
	if request.user.id ==  project[0].owner.id:
		user_is_project_owner = 1
		exclude_this = [request.user.id, project[0].owner.id]
		all_workers = User.objects.exclude(id__in = exclude_this)
		
		workers_from_same_company = all_workers.filter(company = request.user.company)
		workers_from_different_company = all_workers.exclude(company = request.user.company)

		workers_from_same_company = workers_from_same_company.difference(project_workers)
		workers_from_different_company = workers_from_different_company.difference(project_workers)
		
		no_of_project_workers = len(project_workers)
		no_of_workers_from_same_company = len(workers_from_same_company)
		no_of_workers_from_different_company = len(workers_from_different_company)
		
		return render(request, 'pms/projectdetails.html', {'project': project,'project_workers': project_workers, 'project_statuses': project_statuses, 'user_is_project_owner': user_is_project_owner,
							'workers_from_same_company': workers_from_same_company, 'workers_from_different_company': workers_from_different_company, 
							'n_p_w': no_of_project_workers,'n_w_s_c': no_of_workers_from_same_company, 'n_w_d_c': no_of_workers_from_different_company,
							'number_of_notifications': get_no_of_notifications(request)})
	else:
		user_is_project_owner = 0
		no_of_project_workers = len(project_workers)
		return render(request, 'pms/projectdetails.html', {'project': project,'project_workers': project_workers, 'user_is_project_owner': user_is_project_owner, 'n_p_w': no_of_project_workers, 'number_of_notifications': get_no_of_notifications(request)})


@login_required(login_url='index')
def AddNewLevelView(request, projectid):
	if request.method == "POST":
		p = Project.objects.get(id = projectid)
		pl = ProjectLevel.objects.create(level_tag = request.POST["leveltag"])
		p.all_status.add(pl)
		p.save()
		return redirect("projectdetails", projectid=projectid)



@login_required(login_url='index')
def MoveProjectView(request, projectid, levelid):
	p = Project.objects.get(id = projectid)
	l = ProjectLevel.objects.get(id = levelid)
	p.current_status = l
	p.save()
	return redirect("projectdetails", projectid=projectid)


@login_required(login_url='index')
def ChangeProjectDetailsView(request, projectid):
	project_owner_id , project_owner_username = get_project_owner_id_username(projectid)
	if request.user.id == project_owner_id:
		project = Project.objects.get(id = projectid)
		if request.method == "POST":
			project.name = request.POST['name']
			project.description = request.POST['description']
			project.save()
			return redirect("projectdetails", projectid=projectid)
		else:
			return render(request, 'pms/changeprojectdetails.html', {'projectid': projectid, 'name': project.name, 'description': project.description, 'number_of_notifications': get_no_of_notifications(request)})
	else:
		return redirect("projectdetails", projectid=projectid)



@login_required(login_url='index')
def AddWorkersView(request, projectid, workerid):
	project_owner_id , project_owner_username = get_project_owner_id_username(projectid)
	if (request.user.id ==  project_owner_id) and (request.user.id != workerid):
		worker = User.objects.get(id = workerid)
		project = Project.objects.get(id = projectid)
		if not worker_already_in_project(project, worker):
			project.workers.add(worker)
			Notification.objects.create(recipient = worker, content = str(project_owner_username) + " added you in a project.")
			messages.success(request, str(worker.username) + " added to project!")
	return redirect('projectdetails', projectid = projectid)


@login_required(login_url='index')
def RelieveFromProjectView(request, projectid, workerid):
	project_owner_id , project_owner_username = get_project_owner_id_username(projectid)
	if request.user.id ==  project_owner_id:
		project = Project.objects.get(id = projectid)
		worker = project.workers.get(id = workerid)
		project.workers.remove(worker)
		Notification.objects.create(recipient = worker, content = str(project_owner_username) + " relieved you from a project")
		messages.error(request, str(worker.username) + " relieved from project!")
	return redirect('projectdetails', projectid = projectid)


@login_required(login_url='index')
def NotificationsView(request):
	all_notifications = Notification.objects.filter(recipient = request.user)
	read_notifications = all_notifications.filter(read = True)
	unread_notifications = all_notifications.filter(read = False)
	return render(request, 'pms/notifications.html', {'read_notifications': read_notifications, 'unread_notifications': unread_notifications, 'number_of_notifications': get_no_of_notifications(request)})


@login_required(login_url="index")
def NotificationMarkAsReadView(request, notificationid):
	notification = Notification.objects.get(id = notificationid)
	if request.user == notification.recipient:
		notification.read = True
		notification.save()
		messages.warning(request, "Marked as Read!")
		return redirect('notifications')



# AUTHENTICATION

def LoginView(request):
	if request.user.is_authenticated:
		return redirect("home")
	
	else:
		if request.method == "POST":
			username = request.POST.get("username")
			password = request.POST.get("password")

			user = authenticate(request, username = username, password = password)

			if user is not None:
				login(request, user)
				return redirect("home")
			else:
				messages.error(request, "Username or Password is WRONG!")
				return redirect("login")
	
	return render(request, 'pms/login.html')


def LogoutView(request):
	logout(request)
	return redirect("login")


def RegisterView(request):
	if request.user.is_authenticated:
		logout(request)
		
	form = UserRegistrationForm()
	if request.method == "POST":
		form = UserRegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Account Created Successfully! Login Now!')
			return redirect("login")
	
	return render(request, 'pms/register.html', {'form':form})

pms/templates/pms/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

  </head>
  <body>
  {% if user.is_authenticated %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" disabled>PMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}" style="margin-right:40px;">Home</a>
        </li>
		<li class="nav-item">
          <a class="btn btn-outline-success text-white nav-link active" aria-current="page" href="{% url 'createproject' %}" style="margin-right:40px;">+ New Project</a>
        </li>
		<li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'projects' %}" style="margin-right:40px;">Projects</a>
        </li>
		<li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'notifications' %}" style="margin-right:40px;">Notifications
		  			<span class="badge bg-danger" id="no_of_notifications"></span>
		  </a>
		</li>
		<li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
        </li>
		</ul>
    </div>
  </div>
</nav>
{% endif %}

	{% block content %}
	{% endblock %}

	<!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

pms/templates/pms/changeprojectdetails.html
{% extends 'pms/base.html' %}

{% block content %}
<title>Change Project Details</title>
	<br>
	<center>
	<h1>Change Project details..</h1>
	<br><br>
	<div class="card" style="width:500px;">
	<form method = 'POST' class = "form-group" action = "{% url 'changedetails' projectid=projectid %}">
	{% csrf_token %}
		<input type="text" name="name" value="{{ name }}" class="form-control" placeholder="Project Name" maxlength="255" required id="name" style="margin-bottom:5px;">
		<input type="text" name="description" value="{{ description }}" class="form-control" placeholder="A Short Description about the project." maxlength="255" required id="description" style="margin-bottom:5px;">
		<button type = "submit" class="btn btn-info" style="margin-bottom:5px;">Change details</button>
	</form>
	</div>
	</center>
	<script>
			if({{ number_of_notifications }} != 0){
				document.getElementById('no_of_notifications').innerHTML = {{number_of_notifications}};
			}
	</script>

{% endblock %}

pms/templates/pms/createproject.html
{% extends 'pms/base.html' %}

{% block content %}
<title>Create a project</title>
	<br>
	<center>
	<h1>Create a New Project..</h1>
	<br><br>
	<div class="card" style="width:500px;">
	<form method = 'POST' class = "form-group" action = "/createproject/">
	{% csrf_token %}
		<input type="text" name="name" class="form-control" placeholder="Project Name" maxlength="255" required id="name" style="margin-bottom:5px;">
		<input type="text" name="description" class="form-control" placeholder="A Short Description about the project." maxlength="255" required id="description" style="margin-bottom:5px;">
		<button type = "submit" class="btn btn-success" style="margin-bottom:5px;">Create</button>
	</form>
	</div>
	</center>
	<script>
			if({{ number_of_notifications }} != 0){
				document.getElementById('no_of_notifications').innerHTML = {{number_of_notifications}};
			}
	</script>

{% endblock %}

pms/templates/pms/home.html
{% extends 'pms/base.html' %}

{% block content %}
	<title>Home</title>
	<br><br><br><br><br>
	<center>
		<h2>You are currently involved in {{ n_p_i }} Projects!</h2>
	</center>

	<script>
		if({{ number_of_notifications }} != 0){
			document.getElementById('no_of_notifications').innerHTML = {{number_of_notifications}};
		}
	</script>
{% endblock %}

pms/templates/pms/index.html
{% extends 'pms/base.html' %}

{% block content %}
<title>PMS - a project management system</title>
	<center>
	<br><br><br>
	<h1 class="text text-success"><u>PMS</u></h1>
	<i>A Simple Project Managing Tool</i>
	<br>
	<br>
	<div class="container">
		<div class="row">
			<div class="col border-end border-success">
				New User?
				<div class ="block">
					Then <b>Register</b> Here
				</div> 
				<br><br>
				<div class ="block">
					<a href="{% url 'register' %}" class="btn btn-warning">Register</a>
				</div> 
				
			</div>
			<div class="col">
				Already Have an account?
				<div class ="block">
					Then <b>Login</b> Here
				</div> 
				<br><br>
				<div class ="block">
					<a href="{% url 'login' %}" class="btn btn-primary">Login</a>
				</div> 
			</div>
		</div>
	</div>
	</center>
{% endblock %}

pms/templates/pms/login.html
{% extends 'pms/base.html' %}

{% block content %}
	<title>Login</title>
	<center>
	<h1>Login to <a href="{% url 'index' %}" class="text text-success"> PMS </a></h1>
	<hr>
	<br><br><br>
	{% for message in messages %}
			{% if message.level_tag == 'success'%}
			<div class="alert alert-primary" role="alert">
  							{{ message }}
			</div>
			{% else %}
				<div class="alert alert-danger" role="alert">
  							{{ message }}
			</div>
			{% endif %}
	{% endfor %}
	<div class="card" style="width:500px;">
	<form method = 'POST' class = "form-group">
	{% csrf_token %}
		<input type="text" name="username" class="form-control" placeholder="Username" autofocus autocapitalize="none" autocomplete="username" maxlength="255" required id="id_username" style="margin-bottom:5px;">
		<input type="password" name="password" class="form-control" placeholder="Password" autocomplete="current-password" required id="id_password" style="margin-bottom:5px;">
		<button class="btn btn-primary" style="margin-bottom:5px;">Login</button>
		{{ form.errors }}
	</form>
	Didn't Have an PMS account? <a href="{% url 'register'%}" style="margin-bottom:5px;">Register now</a>
	</div>
	</center>

{% endblock %}

pms/templates/pms/notifications.html
{% extends 'pms/base.html' %}

{% block content %}
<title>Notifications</title>
<center>
<br>
<h2>My Notifications</h2>
<br><br>
{% for message in messages %}
	<div class = "alert alert-warning">{{ message }}</div>
	<br>
{% endfor %}

{% for notification in notifications %}
	<div class = "block">{{ notification.content }}</div>
{% endfor %}

<div class="container">
		<div class="row">
			<div class="col border-end border-success">
				<div class ="block">
					<b>New and Unread Notifications</b>
				</div> 
				<br><br>
				<div class ="block">
					<ol>
				  	{% for notification in unread_notifications %}
						<li><div class = "block">{{ notification.content }} - <a href="{% url 'markasread' notificationid=notification.id %}">mark as read</a></div></li>
							{{ notification.date_created|date:"d-m-Y" }}
							<hr>
					{% endfor %}
				  	</ol>
				</div> 
				
			</div>
			<div class="col">
				<div class ="block">
					<b>Old Notifications</b>
				</div> 
				<br><br>
				<div class ="block">
					<ol>
				  	{% for notification in read_notifications %}
						<li><div class = "block">{{ notification.content }}</div></li>
						{{ notification.date_created|date:"d-m-Y" }}
						<hr>
					{% endfor %}
				  	</ol>
				</div> 
			</div>
		</div>
	</div>
	<script>
		if({{ number_of_notifications }} != 0){
			document.getElementById('no_of_notifications').innerHTML = {{number_of_notifications}};
		}
	</script>

{% endblock %}

pms/templates/pms/projectdetails.html
{% extends 'pms/base.html' %}

{% block content %}
<title>Project Details</title>
	<br>
	<center>
	<h1>Project Details</h1>
	{% for message in messages %}
		{% if message.level_tag == 'success' %}
			<div class = "alert alert-success">{{ message }}</div>
		{% else %}
			<div class = "alert alert-danger">{{ message }}</div>
		{% endif %}
	{% endfor %}
	<br><br>
	<div class = "container">
		{% for detail in project %}
			<div class="row" style="margin-bottom:20px;">
    			<div class="col border border-dark">
					<b>Project Name</b>
				</div>
				<div class="col border border-dark">
					{{ detail.name }}
				</div>
			</div>
			<div class="row" style="margin-bottom:20px;">
    			<div class="col border border-dark">
					<b>Project Description</b>
				</div>
				<div class="col border border-dark">
					{{ detail.description }}
				</div>
			</div>
			<div class="row" style="margin-bottom:20px;">
    			<div class="col border border-dark">
					<b>Project Owner</b>
				</div>
				<div class="col border border-dark">
					{{ detail.owner }}
				</div>
			</div>
			<div class="row" style="margin-bottom:20px;">
    			<div class="col border border-dark">
					<b>Project Levels</b>
				</div>
				{% for status in project_statuses %}	
					<div class="col border border-dark">
						{% if status.level_tag|stringformat:'s' == detail.current_status|stringformat:'s' %}
							<p>{{ status.level_tag }}</p>
							<b>(Current Status)</b>
						{% else %}
							<p>{{ status.level_tag }}</p>
							<a href="{% url 'moveproject' projectid=detail.id levelid=status.id %}">Move project here</a>
						{% endif %}
					</div>
				{% endfor %}
				<div class="col border border-dark">
						<button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target= "#exampleModal">Create a new level</button>
								<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
									<div class="modal-dialog">
										<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title" id="exampleModalLabel">Create a new level</h5>
											<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
										</div>
										<div class="modal-body">
											<form method = 'POST' class = "form-group" action = "{% url 'addnewlevel' projectid=detail.id %}">
												{% csrf_token %}
												<input type="text" name="leveltag" class="form-control">
												<div class="modal-footer">
													<button type="submit" class="btn btn-primary">Create</button>
												</div>
											</form>
										</div>
										</div>
									</div>
								</div> 
				</div>
			</div>
	
			
			{% if user_is_project_owner %}

			<a href = "{% url 'changedetails' projectid=detail.id %}">Edit (Project Name or Project Description)</a>

			{% endif %}
			<br><br>

	
			<div class="accordion" id="accordionExample">
				<div class="accordion-item">
    				<h2 class="accordion-header" id="headingOne">
      					<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        					Show workers of this project
      					</button>
    				</h2>
    				<div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      					<div class="accordion-body">
							{{ n_p_w }} available.
						  {% for worker in project_workers %}
								<div class="row" style="margin-bottom:20px;">
									<div class="col">
										{{ worker.username }}
									</div>
									{% if user_is_project_owner %}
    								<div class="col">
										{% comment %} <a href = "relieveworkers/{{ detail.id }}/{{ worker.id }}/" class = "btn btn-danger">Relieve From Project</a> {% endcomment %}
										<a href = "{% url 'relieveworker' projectid=detail.id workerid=worker.id%}" class = "btn btn-danger">Relieve From Project</a>

									</div>
									{% endif %}
								</div>
								{% endfor %} 
      					</div>
    				</div>
  				</div>
				{% if user_is_project_owner %}
  				<div class="accordion-item">
    				<h2 class="accordion-header" id="headingTwo">
      					<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        					Add NEW workers from <b style = "padding-left:20px; padding-right:20px;">{{request.user.company}}</b> Company
      					</button>
    				</h2>
    				<div id="collapseTwo" class="accordion-collapse collapse " aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      					<div class="accordion-body">
						  {{ n_w_s_c }} available.
        						{% for worker in workers_from_same_company %}
								<div class="row" style="margin-bottom:20px;">
									<div class="col">
										{{ worker.username }}
									</div>
    								<div class="col">
										{% comment %} <a href = "addworkers/{{ detail.id }}/{{ worker.id }}" class = "btn btn-warning text-white">Add to project</a> {% endcomment %}
										<a href = "{% url 'addworker' projectid=detail.id workerid=worker.id %}" class = "btn btn-warning text-white">Add to project</a>

									</div>
								</div>
								{% endfor %} 
						</div>
    				</div>
					<div class="accordion-item">
    				<h2 class="accordion-header" id="headingThree">
     					<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        					Add NEW workers from <b style = "padding-left:20px; padding-right:20px;">other</b> Companies
      					</button>
    				</h2>
					<div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">      					
							<div class="accordion-body">
							{{ n_w_d_c }} available.
        						{% for worker in workers_from_different_company %}
								<div class="row" style="margin-bottom:20px;">
									<div class="col">
										{{ worker.username }}
									</div>
    								<div class="col">
										<a href = "{% url 'addworker' projectid=detail.id workerid=worker.id %}" class = "btn btn-warning text-white">Add to project</a>
									</div>
								</div>
								{% endfor %} 
						</div>
    				</div>
				{% endif %}
  			</div>
	
	{% endfor %}
	</center>
	<script>
		if({{ number_of_notifications }} != 0){
			document.getElementById('no_of_notifications').innerHTML = {{number_of_notifications}};
		}
	</script>


{% endblock %}

pms/templates/pms/projects.html
{% extends 'pms/base.html' %}

{% block content %}
<title>Projects</title>
	<br><br>
	<center>
		<div class="container">
		<div class="row">
			<div class="col border-end border-success">
				<div class ="block">
					<b>Projects as Owner ({{number_of_projects_as_owner}})</b>
				</div> 
				<br><br>
				<div class ="block">
					<ol>
				  	{% for project in projects_as_owner %}
						<li><a href = "{% url 'projectdetails' projectid=project.id %}">{{ project.name }}</a></li>
					{% endfor %}
				  	</ol>
				</div> 
				
			</div>
			<div class="col">
				<div class ="block">
					<b>Projects as Worker ({{number_of_projects_as_worker}})</b>
				</div> 
				<br><br>
				<div class ="block">
					<ol>
				  	{% for project in projects_as_worker %}
						<li><a href = "{% url 'projectdetails' projectid=project.id %}">{{ project.name }}</a></li>
					{% endfor %}
				  	</ol>
				</div> 
			</div>
		</div>
	</div>
	</center>

	<script>
		if({{ number_of_notifications }} != 0){
			document.getElementById('no_of_notifications').innerHTML = {{number_of_notifications}};
		}
	</script>
	
	
{% endblock %}

pms/templates/pms/register.html
{% extends 'pms/base.html' %}




{% block content %}
<title>Register</title>
	
	<style>
			.errorlist{
				color:red;
			}
	</style>
	<body>
	<center>
	<h1>Register Now on <a href="{% url 'index' %}" class="text text-success"> PMS </a></h1>
	<hr>
	<div class="card" style="width:500px;">
	<form method = 'POST' class = "form-group">
	 {% csrf_token %}
		<input type="text" name="username" class="form-control" placeholder="Username"  maxlength="255" autofocus required id="id_username" style="margin-bottom:5px;">
		<input type="text" name="firstname" class="form-control" placeholder="First Name" maxlength="255" required id="id_firstname" style="margin-bottom:5px;">
		<input type="text" name="lastname" class="form-control" placeholder="Last Name" maxlength="255" required id="id_lastname" style="margin-bottom:5px;">
		<input type="email" name="email" class="form-control" placeholder="Email" maxlength="255" required id="id_email" style="margin-bottom:5px;">
		<input type="text" name="company" class="form-control" placeholder="Company Name" required id="id_company" style="margin-bottom:5px;">
		<input type="password" name="password1" class="form-control" placeholder="Password" autocomplete="new-password" required id="id_password1" style="margin-bottom:5px;"> 
		<input type="password" name="password2" class="form-control" placeholder="Password Confirmation" autocomplete="new-password" required id="id_password2" style="margin-bottom:5px;">
	    <button class="btn btn-warning" style="margin-bottom:5px; margin-top:5px;" id="register-button">Register</button>
		
		{{ form.errors }}
		
	</form>
	Already Have an PMS account? <a href="{% url 'login'%}" style="margin-bottom:5px;">Login now</a>
	</div>
	</center>
	</body>
{% endblock %}